# Generated by Django 5.0.6 on 2024-06-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeID', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('AddressLine', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('phone_number', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
